name: '🌃️  Nightly'
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # ref: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '0 0 * * 1'
jobs:
  release:
    name: '🌃️  Nightly'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    steps:
      - name: '🐙️  Git Checkout'
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch.
          # 0 indicates all history for all branches and tags.
          fetch-depth: 5

      - name: '🔧️ Setup Node: ${{ matrix.node }}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # architecture: 'x64'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      # - name: '🌵️  Cache-tus'
      #   uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: '🔺️  Cache-turbo'
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: '📦️ Install Dependecies'
        run: |
          yarn install --frozen-lockfile --ignore-engines --network-concurrency 1

      - name: '🚨️  Lint'
        run: |
          yarn lint --cache-dir=".turbo"

      # todo(ci) turn off for now please
      # - name: '⚗️  Test'
      #   run: |
      #     yarn test

      - name: '🏗️  Build'
        run: |
          yarn build --cache-dir=".turbo"

      - name: '🏷️  Semantic Release'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo "@jeromefitz:registry=https://registry.npmjs.org/" >> .npmrc
          yarn semantic-release
