name: '⚗️ Pull Request'
on:
  pull_request:
    branches:
      - main
      - canary
      - develop
jobs:
  release:
    name: '⚗️ Pull Request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    steps:
      - name: '🐙️  Git Checkout'
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch.
          # 0 indicates all history for all branches and tags.
          fetch-depth: 5

      - name: '🔧️ Setup Node: ${{ matrix.node }}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # architecture: 'x64'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      # - name: '🌵️  Cache-tus'
      #   uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: '🔺️  Cache-turbo'
        id: turbo-cache-pull
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: '📦️ Install Dependecies'
        run: |
          yarn install --frozen-lockfile --ignore-engines --network-concurrency 1

      - name: '🚨️  Lint'
        run: |
          yarn lint --cache-dir=".turbo"

      # todo(ci) turn off for now please
      # - name: '⚗️  Test'
      #   run: |
      #     yarn test
