name: '  ▶️  Pull'

on:
  pull_request:
    branches:
      - main
      - canary
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft

concurrency:
  group: pull-${{ github.ref }}-1
  cancel-in-progress: true

env:
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  pull:
    name: '👷️  CI'
    if: github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '[skip ci]')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      IS_ACTOR_VERIFIED: ${{ github.actor == 'jeromefitz' || github.actor == 'dependabot[bot]' }}
      IS_ACTOR_JEROMEFITZ: ${{ github.actor == 'jeromefitz' }}
      IS_ACTOR_DEPENDABOT: ${{ github.actor == 'dependabot[bot]' }}
      IS_ACTOR_RENOVATE: ${{ github.actor == 'renovate[bot]' }}
      IS_LABEL_PNPM: ${{ contains( github.event.pull_request.labels.*.name, '📦 pnpm' ) }}
    steps:
      - name: '🐙️  Checkout'
        id: pull-checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: '💽️  Init'
        id: pull-init
        uses: JeromeFitz/packages/.github/actions/init@renovate/configure

      - name: '🚚💨 debug'
        id: pull-debug
        shell: bash
        run: |
          echo 'IS_ACTOR_VERIFIED: ${{ env.IS_ACTOR_VERIFIED }}'
          echo 'IS_ACTOR_JEROMEFITZ: ${{ env.IS_ACTOR_JEROMEFITZ }}'
          echo 'IS_ACTOR_DEPENDABOT: ${{ env.IS_ACTOR_DEPENDABOT }}'
          echo 'IS_LABEL_PNPM: ${{ env.IS_LABEL_PNPM }}'
          echo 'github.actor: ${{ github.actor }}'

      - name: '🚚💨 debug ii'
        id: pull-debug-ii
        if: ${{ env.IS_ACTOR_JEROMEFITZ == 'true' }}
        shell: bash
        run: |
          echo 'Verify strings or booleans: STRING'

      - name: '🚚💨 debug iii'
        id: pull-debug-iii
        if: ${{ env.IS_ACTOR_JEROMEFITZ == true' }}
        shell: bash
        run: |
          echo 'Verify strings or booleans: BOOLEAN'

      - name: '🔒  pnpm'
        id: pull-pnpm
        uses: JeromeFitz/packages/.github/actions/pnpm@renovate/configure
        if: ${{ env.IS_ACTOR_DEPENDABOT == 'true' || env.IS_LABEL_PNPM == 'true' }}
        with:
          IS_ACTOR_VERIFIED: ${{ env.IS_ACTOR_VERIFIED }}
          IS_ACTOR_JEROMEFITZ: ${{ env.IS_ACTOR_JEROMEFITZ }}
          IS_ACTOR_DEPENDABOT: ${{ env.IS_ACTOR_DEPENDABOT }}
          IS_LABEL_PNPM: ${{ env.IS_LABEL_PNPM }}

      - name: '📦  Install'
        id: pull-install
        uses: JeromeFitz/packages/.github/actions/install@renovate/configure

      - name: '🔺️  Cache (turbo)'
        id: pull-cache-turbo
        uses: JeromeFitz/packages/.github/actions/cache-turbo@renovate/configure
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: '🚨️  Lint'
        id: pull-lint
        uses: JeromeFitz/packages/.github/actions/lint@renovate/configure
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
